#should deny
name: Verify
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Prepare repository
        uses: actions/checkout@v3
         
      - name: Install dependencies
        run: |
          sudo apt install -y unzip jq
      
      - name: Run verify script
        run: |
          bash scripts/verify.sh
          if [ $? -eq 1 ]; then
            exit 1
          fi
